CREATE TABLE IF NOT EXISTS ADDRESS (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  STREET VARCHAR(50) NOT NULL,
  STREET_NUMBER VARCHAR(10),
  CITY VARCHAR(20) NOT NULL,
  ZIP_CODE VARCHAR(10) NOT NULL,
  COUNTRY VARCHAR(20) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  ID_ADDRESS BIGINT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(ID_ADDRESS) REFERENCES ADDRESS(ID)
);