CREATE TABLE IF NOT EXISTS PRODUCT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CATEGORY (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORIES (
  ID_PRODUCT BIGINT NOT NULL,
  ID_CATEGORY BIGINT NOT NULL,
  PRIMARY KEY(ID_PRODUCT, ID_CATEGORY),
  FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(ID),
  FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(ID)
);